{ AccCode             :  "Access Code"
, AccHis              :  "Account History"
, AccounNum           :  "Account Number"
, Address             :  "Address"
, Age                 :  "Age"
, Alias               :  "Alias"
, AlienRegNum         :  "Alien Registration Number"
, AppellationCode     :  "Appellation Code"
, ApplHist            :  "Application and Claims History, Including any Appeals Records."
, ApplName            :  "Application Name"
, ApplNum             :  "Application Number/e-form number"
, ApplRegNum          :  "Application Registration Number"
, AreaCode            :  "Area Code"
, AttendanceDate      :  "Dates of Attendance"
, Awards              :  "Awards "
, BarcodeNum          :  "Barcode Number"
, BidOpenDate         :  "Bid Opening Date"
, BillInfo            :  "Billing Information at the Clinic"
, BiomRec             :  "Biometric Records"
, Birthplace          :  "Birth place (country/state/city)"
, CardCode            :  "Card Validation Codes / Values"
, CardName            :  "Cardholder name"
, CardStrip           :  "Cardholder Data - Full magnetic stripe"
, CaseloadNum         :  "Caseload Number"
, CaseNum             :  "Case Number"
, CaseRecName         :  "Case Record Name"
, CaseRecNum          :  "Case Record Number"
, CheckNum            :  "Check Number"
, ChildCareAddr       :  "Childcare Facility Address"
, CHIPContCode        :  "CHIP Contractor Code"
, CISAppNum           :  "CIS Application Number"
, CISRecNum           :  "CIS Record Number"
, Citizen             :  "Citizenship"
, CitizenCode         :  "Citizenship Code"
, CitizenStatus       :  "Citizenship Status"
, City                :  "City Township"
, CivilSubdiv         :  "Civil Subdivision"
, Comm                :  "Commodity Specialist"
, CommOrgName         :  "Community Based Organization Name"
, CommPartnerId       :  "Community Partner Organization ID"
, CommPartUserId      :  "Community Partner User ID"
, COMPIdNum           :  "COMPASS Individual Number"
, CompletTrackData    :  "Complete Track Data"
, ConsumerCredit      :  "Consumer’s Credit Worthiness"
, contact3rd          :  "Third Person Contact"
, ContractNo          :  "Contract No."
, CountryCode         :  "County Code"
, CountryOrigin       :  "Country of Origin"
, County              :  "County"
, CourtNameNum        :  "Court Name/Court order number"
, CreditCap           :  "Credit Capacity"
, CreditCardNum       :  "Credit Card Number"
, CreditScore         :  "Credit Score"
, CreditStanding      :  "Credit Standing"
, CriminalConv        :  "Criminal convictions"
, CriminalHist        :  "Criminal History"
, DateofDeath         :  "Date of Death"
, DebitCardNum        :  "Debit Card Number"
, Degree              :  "Degree"
, DemographInfo       :  "Demographic Information"
, DiagnosisRep        :  "Diagnosis Report"
, DisabilityCode      :  "Disability Code"
, DistrictOffice      :  "District Office"
, DNA                 :  "DNA Sequence"
, DOB                 :  "Date of Birth"
, DocID               :  "Document ID"
, DriverLicenseNum    :  "Driver’s license"
, DrugAbuseInfo       :  "Drug and alcohol abuse information"
, EBTNum              :  "EBT card number"
, EdAgency            :  "Educational Agency"
, ElectronicComm      :  "Electronic Communication"
, Elevation           :  "Elevation"
, EmailAddr           :  "Email Address"
, EmailComm           :  "Email Communication"
, EmplAddr            :  "Employer Address"
, EmplID              :  "Employer Identifier"
, EmplName            :  "Employer Name"
, EmplPhone           :  "Employer Contact Phone Number"
, EmplSN              :  "Employer Sequence Number"
, EnrollStatus        :  "Enrollment Status"
, ExpireDate          :  "Expiration date"
, Facial              :  "Facial Characteristics"
, FamilyName          :  "Name of Parents/Family Members"
, Fax                 :  "Fax Number"
, FederalTaxWith      :  "Federal Tax Withholdings"
, FEIN                :  "FEIN"
, FFMIN               :  "FFM Individual Number"
, FinancAcctnum       :  "Financial account number"
, Finger              :  "Finger Prints"
, FinInstName         :  "Name of Financial Institution"
, FirstName           :  "First Name"
, FuneralHome         :  "Funeral Home name"
, GeneMark            :  "Genetic Marker"
, GeneTest            :  "Genetic Testing Information"
, Geographic          :  "Geographic Indicators"
, GradLevel           :  "Grade Level"
, GroupNum            :  "Group Number"
, HandWriting         :  "Handwriting"
, HealthSvcs          :  "Health Services provided"
, HeatingAcctNum      :  "Heating Provider Account Number"
, Height              :  "Height of Members"
, HIPN                :  "Health Insurance Policy Number "
, HouseDisable        :  "Household Disability Indicator"
, HouseNum            :  "Household Number"
, HPB                 :  "Health Plan Beneficiary"
, HPIP                :  "Health Plan Insurance Premium"
, I551                :  "I551 Card Number"
, I94                 :  "I94 Document Number"
, Income              :  "Income"
, IncomeGross         :  "Income/Gross"
, IncomeMonth         :  "Income/Monthly Income"
, IndivNum            :  "Individual Number"
, InstAttend          :  "Institution Attended"
, Insurer             :  "Insurance Provider/Insurance Company Name"
, InsurerAddr         :  "Insurance Address"
, InsurerCarrier      :  "Insurance Carrier"
, IPAddr              :  "Internet Protocol Address"
, Language            :  "Language"
, LastName            :  "Last Name"
, LastName2           :  "Second Last Name"
, Latitude            :  "Latitude"
, LegalEntity         :  "Legal Entity - Service Location"
, Longitude           :  "Longitude"
, Major               :  "Major Field of Study"
, MaritalStatus       :  "Marital Status"
, MasterProvINum      :  "Master Provider Index Number"
, MCINum              :  "MCI Number"
, MedCond             :  "Medical Condition/Disability Description"
, MedFacilityAddr     :  "Doctor/Clinic/Nursing facility Address"
, MedFacilityName     :  "Doctor/Clinic/Nursing facility Name"
, MedHist             :  "Medical History"
, MedicareId          :  "Medicare ID"
, MedicClaimNum       :  "Medicare Claim Number"
, MedicProvId         :  "Medicaid Provider ID"
, MedInfo             :  "Medical Information"
, MedLicNum           :  "Medical License Number"
, MedProvider         :  "Medical Provider information (name, address, phone number)"
, MedRecNum           :  "Medical Record Number"
, MedTreatDiagInf     :  "Medical Treatment or Diagnosis Information"
, MentalCond          :  "Mental Condition Information"
, MiddleInit          :  "Middle Initial"
, MiddleName          :  "Middle Name"
, ModeLiving          :  "Mode of Living"
, MomMaiden           :  "Mother Maiden Name"
, MVReg               :  "Motor Vehicle Registration "
, NonCitizenID        :  "Non citizen Registration ID"
, NoticeID            :  "Notification Identifier"
, Offenses            :  "Offenses"
, OralComm            :  "Oral Communication"
, OrgName             :  "Name of Organization of Sponsor"
, ParentNum           :  "Parent No. "
, ParoleNum           :  "Parole Number"
, Participation       :  "Participation in Officially Recognized Activities and Sports"
, PassportExp         :  "Passport Expiration date"
, PassportNum         :  "Passport Number"
, Password            :  "Password"
, PatientAcctNum      :  "Patient Account Number"
, PayHealth           :  "Payment of Health Care Provisions"
, PaymentName         :  "Payment Name"
, PaymentNum          :  "Payment Number"
, PayRate             :  "Pay Rate"
, Phone               :  "Phone Number"
, Phone3rd            :  "Third Person Phone"
, PhoneCalls          :  "Telephone Conversations"
, PhoneExt            :  "Phone Extension"
, PhoneHome           :  "Home Phone Number"
, PhoneListing        :  "Telephone Listing"
, Photo               :  "Photograph"
, PhysicalCond        :  "Physical Condition Information"
, PIFN                :  "Personally Identifiable Financial Information"
, PIN                 :  "PIN - Personal Identification Number "
, PINblocks           :  "PIN Blocks"
, PinkSlip            :  "Motor Vehicle Title "
, PlaceOfBirth        :  "Place of Birth"
, PlaceParole         :  "Place of parole/probabtion (state,county,jurisdiction)"
, PolicyGroupNum      :  "Policy Group Number"
, PolicyId            :  "Policy ID"
, PolicyNum           :  "Policy Number"
, PoliticalParty      :  "Party Affiliation"
, PostCode            :  "PostCode"
, PrimaryAcctNum      :  "PAN - Primary Account Number  / Account Number"
, PriorName           :  "Maiden or Prior Name"
, PrisonerNum         :  "Prisoner Number"
, PrivatePIN          :  "Nonpublic Personal Information"
, ProcurementNum      :  "Procurement No."
, ProviderAddr        :  "Provider Address"
, ProviderMAID        :  "Provider M.A.I.D Number"
, ProviderName        :  "Provider Name"
, ProviderNum         :  "Provider Number"
, ProviderPhone       :  "Provider Phone"
, Race                :  "Racial/ Ethnic origin"
, RealtorName         :  "Realtor Name"
, RealtorPhone        :  "Realtor Phone Number"
, RecNum              :  "Record Number in Upload File/Record Number"
, Religion            :  "Religious/ Philosophical beliefs"
, Reputation          :  "Character/ General Reputation/ Personal Characteristics"
, Retina              :  "Retina and Iris Patterns"
, ReviewId            :  "Reviewer User ID"
, SatVid              :  "Private Satellite Video Communication "
, SchBuildName        :  "School Building Name"
, SchCode             :  "School Code"
, SchCountyCode       :  "School County Code"
, SchDistCode         :  "School District"
, SchDistCode         :  "School District Code"
, SchName             :  "School Name"
, ScreenNum           :  "Screening Number"
, SecCode             :  "Security Code"
, ServiceCode         :  "Service Code"
, Sex                 :  "Gender"
, SexOrientation      :  "Health/ Sexual orientation"
, SNAP                :  "SNAP or TANF case number"
, SoldPropDes         :  "Sold Property Description"
, SSA                 :  "SSA Verification Identifier"
, SSN                 :  "SSN - Social Security Number"
, State               :  "State"
, StateID             :  "State Identification Number"
, StateTax            :  "State Tax data"
, StudIN              :  "Student Identification Number"
, SubsIN              :  "Subscriber Identification Number"
, Suffix              :  "Suffix"
, TANF                :  "TANF Case Number"
, TargetSysAppID      :  "Target System Application ID"
, TargSysID           :  "Target System Individual ID"
, TIN                 :  "Tax Identification Number"
, TPIN                :  "TIN - Taxpayer Identification Number"
, TradeUnion          :  "Trade-union membership"
, TransData           :  "Transaction Data"
, TribeName           :  "Tribe Name"
, TribeState          :  "Tribe State"
, UFI                 :  "UFI Number"
, Unearned            :  "Unearned Income"
, UniqueID            :  "Unique Identifier "
, User                :  "Username identifier"
, UserHintA           :  "User Hint Answer"
, UserHintQ           :  "User Hint Question"
, UserId              :  "User Logon ID"
, UserIDPartner       :  "User Identity of the Community Partner"
, UserIDSpons         :  "User Identity of Sponsor"
, VendorPhone         :  "Vendor Phone Number"
, VetClaimNum         :  "Veteran Claim Number"
, VIN                 :  "Vehicle Information (Year,make and model)"
, VoicePrint          :  "Voice Prints"
, VoteID              :  "Voter ID number"
, Wage                :  "Wage"
, WebAppNum           :  "Web Application Number"
, Weight              :  "Weight of Members"
, WireCom             :  "Wired Communication"
, ZIP                 :  "ZIP Code"
, ZIPext              :  "ZIP Extension
}
